# secrets.toml
OPENAI_API_KEY = "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"

